src/Entity/Student.php
<?php

namespace App\Entity;
use App\Entity\Staff;
use App\Repository\StudentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;


/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $class;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $section;
    /**
     * @ORM\Column(type="date")
     */
    private $admission_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $parent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

     /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    /**
     * Many features have one product. This is the owning side.
     * @ORM\ManyToOne(targetEntity="App\Entity\Staff", inversedBy="pupils")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $classteacher;


    /**
     * @ORM\Column(type="string")
     */
    private $photoFilename;


    public function getPhotoFilename(){
        return $this->photoFilename;
    }

    public function setPhotoFilename($photoname){
        $this->photoFilename=$photoname;
        return $this;
    }

    
    public function getClassteacher(): ?Staff
    {
        return $this->classteacher;
    }

    public function setClassteacher(?Staff $classteacher): self
    {
        $this->classteacher = $classteacher;

        return $this;
    }
/*    public function setProfilepicture(File $file = null)
    {
        $this->headshot = $file;
    }

    public function getProfilepicture()
    {
        return $this->headshot;
    }
*/
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getClass(): ?int
    {
        return $this->class;
    }

    public function setClass(int $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getSection(): ?string
    {
        return $this->section;
    }

    public function setSection(string $section): self
    {
        $this->section = $section;

        return $this;
    }

    public function getAdmissionDate(): ?\DateTimeInterface
    {
        return $this->admission_date;
    }

    public function setAdmissionDate(\DateTimeInterface $admission_date): self
    {
        $this->admission_date = $admission_date;

        return $this;
    }

    public function getParent(): ?string
    {
        return $this->parent;
    }

    public function setParent(string $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

        /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->name;
        // to show the id of the Category in the select
        // return $this->id;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;
use App\Entity\Student;
use App\Entity\Staff;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Validator\Constraints\File;


class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       

        $builder
            ->add('name', TextType::class)
            ->add('email', EmailType::class)
            ->add('class', IntegerType::class)
            ->add('section', TextType::class)
            ->add('admission_date',DateType::class,[
                'widget' => 'choice',
            ])
            ->add('classteacher', EntityType::class,[
                'class'=>Staff::class,
            ])
            ->add('parent',TextType::class)
            ->add('phone',NumberType::class)
            ->add('studentphoto',FileType::class,[
                'label'=>'Jpeg/PNG photo',
                'mapped'=>false,
                'required'=>false,
                'constraints' => [
                    new File([
                        'maxSize'=>'1024k',
                        'mimeTypes'=>[
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid picture',

                    ])
                ],


            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Confirm Password']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;
use App\Service\PhotoUploader;
use App\Entity\Student;
use App\Entity\User;
use App\Form\StudentType;
use App\Form\StudentEditType;
use App\Form\SearchingType;
use App\Entity\Staff;
use Gedmo\Sluggable\Util\Urlizer;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class StudentController extends AbstractController
{

	private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * @Route("/student", name="student")
     */
    public function index(): Response
    {


        return $this->render('student/index.html.twig', [
            'controller_name' => 'StudentController',
        ]);
    }


    /**
     * @Route("/newstudent", name="newstudent")
     */
    public function registerNew(Request $request, PhotoUploader $photoUploader)
    {
    	$student = new Student();
    	$user = new User();
        $staff = $this->getDoctrine()
                    ->getRepository(Staff::class)
                    ->findAll();
    	$form = $this->createForm(StudentType::class,$student);
    	$form->handleRequest($request);
    	if($form->isSubmitted() && $form->isValid()){
            //do this if an image is uploaded
            $photoFile=$form->get('studentphoto')->getData();
            if($photoFile){
                $photoFileName=$photoUploader->upload($photoFile);
                $student->setPhotoFilename($photoFileName);
            }
        
            // Encode the new users password
           $user->setPassword($this->passwordEncoder->encodePassword($user, $student->getPassword()));
           $user->setEmail($student->getEmail());
           $user->setName($student->getName());


            // Set their role
            $user->setRoles(['ROLE_USER']);

    		$em = $this->getDoctrine()->getManager();
    		$em->persist($student);
    		$em->flush();
    		 $um = $this->getDoctrine()->getManager();
    		 $um->persist($user);
    		 $um->flush();
    		return $this->redirectToRoute('liststudent');
       	}

       	return $this->render('student/register.html.twig',[
       		'form' => $form->createView(),
       	]);
    }

    /**
    * @Route("/student/{id}",name="getstudent")
    */
    public function getStudent(int $id): Response
    {
        //method to get a single student using an id.

        $student = $this->getDoctrine()
                    ->getRepository(Student::class)
                    ->find($id);

        // this creates an exception for the ErrorController to handle
        if(!$student){
            throw $this->createNotFoundException(
                "No product found for id ".$id
            );
        }

        return $this->render('student/show.html.twig',[
            'student' =>$student
        ]);
    }

        /**
    * @Route("/liststudent",name="liststudent")
    */
    public function listStudents(Request $request,PaginatorInterface $paginator)
    {
        //method to list  students 
        $student = new Student();
        $form = $this->createForm(SearchingType::class,$student);
        $form->handleRequest($request);
       
        if($form->isSubmitted() && $form->isValid()){
             //normal query using doctrin
 //            $student = $this->getDoctrine()
  //                  ->getRepository(Student::class)
   //                 ->findBy(['name'=>$student->getName()],
     //                        ['phone' => 'ASC']);

        //complex query using mysql custom query 

//        $student = $this->getDoctrine() -> getRepository(Student::class)
  //                  ->findAllWithName($student->getName());

            //not using DQL language
            
            $repository = $this->getDoctrine() -> getRepository(Student::class);
            
            $query = $repository->createQueryBuilder('p')
            ->where('p.name LIKE :myname')
            ->orWhere('p.parent LIKE :myname')
            ->orWhere('p.phone LIKE :myname')
             ->setParameter('myname', '%'.$student->getName().'%')
            ->orderBy('p.phone', 'ASC')
            ->getQuery();
            $pagination = $paginator->paginate(
            $student = $query->getResult(),$request->query->getInt('page', 1), 5
            );

         return $this->render('student/list.html.twig',[
            
            'form' => $form->createView(),
            'pagination' => $pagination,
        ]);

        }
        $pagination = $paginator->paginate(
        $student = $this->getDoctrine()
                    ->getRepository(Student::class)
                    ->findAll(),$request->query->getInt('page', 1),5                
                );
        if(!$student){
            throw $this->createNotFoundException(
                "No product found for id ".$id
            );
        }
        return $this->render('student/list.html.twig',[
            'form' =>$form->createView(),
            'pagination' =>$pagination,
        ]);
    }

    /**
    * @Route("/delstudent/{id}",name="delstudent")
    */
    public function deleteStudent(int $id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $student = $em ->getRepository(Student::class)->find($id);
        $user = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findOneBy(array('email'=>$student->getEmail()));

        if(!$student){
            throw $this->createNotFoundException(
                "No product found for id ".$id
            );
        }
        $em -> remove($student);
        $em ->remove($user);
        $em ->flush();
        return $this->redirectToRoute('app_login');
    }

    /**
    * @Route("/editstudent/{id}",name="editstudent")
    */
    public function editStudent(int $id,request $request,PhotoUploader $photoUploader): Response
    {
        $em = $this->getDoctrine()->getManager();
        $um = $this->getDoctrine()->getManager();
        $student = $em ->getRepository(Student::class)->find($id);
        if(!$student){
            throw $this->createNotFoundException(
                "This student is non existent for id ". $id
            );
        }
        $user = $um->getRepository(User::class)->findOneBy(array('email'=>$student->getEmail()));
        $form = $this->createForm(StudentEditType::class,$student);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //do this if an image is uploaded
            $photoFile=$form->get('studentphoto')->getData();
            if($photoFile){
                $photoFileName=$photoUploader->upload($photoFile);
                $student->setPhotoFilename($photoFileName);
            }
        

                        // Encode the new users password
           $user->setPassword($this->passwordEncoder->encodePassword($user, $student->getPassword()));
           $user->setEmail($student->getEmail());
           $user->setName($student->getName());


            // Set their role
            $user->setRoles(['ROLE_USER']);

            $em = $this->getDoctrine()->getManager();
            $em->persist($student);
            $em->flush();
             $um = $this->getDoctrine()->getManager();
             $um->persist($user);
             $um->flush();
            return $this->redirectToRoute('liststudent');
        }
        return $this->render('student/edit.html.twig',[
            'form' => $form->createView(),
            'user' => $user->getPassword(),
        ]);

    }

}

templates/student/edit.html.twig
{# templates/registration/index.html.twig #} {% extends 'base.html.twig' %} {%
block body %}
<div class="container">
  <div class="row">
  {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <div class="col-md-10 ml-md-auto">
      <div class="card bg-light mb-3 mt-5" style="width: 800px">
        <div class="card-body">
          <div class="card-header mb-3">Edit Student</div>
          {{ form_start(form) }}
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.class, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.section, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.admission_date, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.studentphoto, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.parent, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
            <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.classteacher, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.phone, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-user"></i> Edit
              </button>
           <button  class="btn btn-Danger">
              <a href="{{ path('liststudent') }}" class="fa fa-btn fa-user">Cancel</a>
            </button>

            </div>
          </div>
          {{ form_end(form) }}

        </div>
         {% else %}
      </div>
    </div>
  </div>
        <div>
      <span>You need to be logged in for this content</span>
      </div>
      <a href="{{ path('app_login') }}" class="btn btn-primary">
         Sign Up >></a
      >

       {% endif %}
</div>
{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StudentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Nischal/PHPprojects/our_school_mgmt/src/Controller/StudentController.php'|file_link(0) }}">src/Controller/StudentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Nischal/PHPprojects/our_school_mgmt/templates/student/index.html.twig'|file_link(0) }}">templates/student/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/student/list.html.twig
{% extends 'base.html.twig' %} 
{% block body %}
<div class="container content ">
  <div class="row scroller ">
   {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <div class="col-md-12 searchholder" >
            {{ form_start(form) }}
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
              <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-user"></i> Search 
              </button>
            </div>
   {{ form_end(form) }}
  </div>
{% endif %}
    <div class="col-md-12 ">
    {% set error='' %}
      <div class="card bg-light mb-3 mt-3 encompass">
        <div class="card-body " style="overflow:auto">
          <div class="card-header">List of Students {{ pagination.getTotalItemCount }}</div>
          {% if is_granted('IS_AUTHENTICATED_FULLY') %}

          <table class="table" >
            <tr>
              <th>Class</th>
              <th>Name</th>
              <th>Section</th>
              <th>Class Teacher</th>
              <th>Delete</th>
              <th>Edit</th>
            </tr>
            {% for key,item in pagination %}
            <tr>
              <td>{{ item.class }}</td>
              <td><a class="nav-link" href="{{path('getstudent',{id:item.id}) }}">{{ item.name }}</td>
              <td>{{ item.section }}</td>
              <td>{{ item.classteacher }}</td>

              <td><a class="nav-link" href="{% if  is_granted('ROLE_ADMIN') %} {{path('delstudent',{id:item.id}) }} {% else %} {{ path('liststudent')}}  {% endif %} ">Delete</a></td>
              <td><a class="nav-link" href="{% if  is_granted('ROLE_ADMIN') %} {{path('editstudent',{id:item.id}) }} {% else %} {% set error = 'need to login as admin for delete and edit ' %}  {% endif %} ">Edit</a></td>
            </tr>
            {% endfor %}
            </table>
           {{ knp_pagination_render(pagination) }}
           {{ error }}
          {% else %}
        </div>
      </div>
      <div>
      <span>You need to be logged in for this content</span>
      </div>
      <a href="{{ path('app_login') }}" class="btn btn-primary">
         Sign In</a
      >

       {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/student/register.html.twig
{# templates/registration/index.html.twig #} {% extends 'base.html.twig' %} {%
block body %}
<div class="container content">
  <div class="row">
    
    <div class="col-md-12">
      <div class="card bg-light mb-3 mt-3">
        <div class="card-body">
          <div class="card-header mb-3">Add New Student</div>
          {% if is_granted('ROLE_ADMIN') %}
          {{ form_start(form) }}
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.class, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.section, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.classteacher, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.studentphoto, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.admission_date, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.parent, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.phone, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.password.first, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.password.second, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-user"></i> Register
              </button>
            </div>
          </div>
          {{ form_end(form) }}
        </div>
         {% else %}

      </div>

    </div>
                          <div>
      <span>You need to be logged in as Admin for this</span>
      </div>
      <a href="{{ path('app_login') }}" class="btn btn-primary">
         Sign In </a
      >

       {% endif %}
  </div>
  </div>

</div>
{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %} 
{% block body %}
<div class="container content">
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-gradient-info bg-info text-white mb-3 mt-3">
        <div class="card-body ">
          <div class="card-header h3 ">{{student.name}}</div>
          {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <ul class="profile left">
            <li> class : {{ student.class }}</li>
            <li> section : {{ student.section }}</li>
            <li class ="bold"> Email: {{ student.email }}</li>
            <li> Phone: {{ student.phone }}</li>
            <li> Class Teacher : {{ student.classteacher }}</li>
            <li> Join Date : {{ student.admissionDate |date('Y-m-d')}}</li>
            </ul>
            <div  class ="studentphoto ">
            {% if student.photoFilename %}
            <img class="headshot" src="{{ asset('uploads/photos/' ~ student.photoFilename) }}" style="color:red"/>
            {% else %}
              <li>No Photo Uploaded</li>
            {% endif %}
            </div>

          {% else %}
        </div>

      </div>
    
      <a href="{{ path('app_login') }}" class="btn btn-info">
        You need to login to see the list 😜😜 >></a
      >
       {% endif %}
    </div>
  </div>
</div>
{% endblock %}