src/Entity/Staff.php
<?php

namespace App\Entity;
use App\Entity\Student;
use App\Repository\StaffRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=StaffRepository::class)
 */
class Staff
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $staff_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

        /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;


        /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

     /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * One product has many features. This is the inverse side.
     * @ORM\OneToMany(targetEntity="App\Entity\Student", mappedBy="classteacher")
     */
    private $pupils;


    /**
     * @ORM\Column(type="string")
     */
    private $brochureFilename;

    

    public function __construct()
    {
        $this->pupils  = new ArrayCollection();
    }

    /**
     * @return Collection|Product[]
     */
    public function getPupils(): Collection
    {
        return $this->pupils;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    
    public function getBrochureFilename()
    {
        return $this->brochureFilename;
    }

    public function setBrochureFilename($brochureFilename)
    {
        $this->brochureFilename = $brochureFilename;

        return $this;
    }

    public function getStaffId(): ?int
    {
        return $this->staff_id;
    }

    public function setStaffId(int $staff_id): self
    {
        $this->staff_id = $staff_id;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }
    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
       public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


        /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }
    public function __toString(){
        // to show the name of the Category in the select
        return $this->name;
        // to show the id of the Category in the select
        // return $this->id;
    }

    public function addPupil(Student $pupil): self
    {
        if (!$this->pupils->contains($pupil)) {
            $this->pupils[] = $pupil;
            $pupil->setClassteacher($this);
        }

        return $this;
    }

    public function removePupil(Student $pupil): self
    {
        if ($this->pupils->removeElement($pupil)) {
            // set the owning side to null (unless already changed)
            if ($pupil->getClassteacher() === $this) {
                $pupil->setClassteacher(null);
            }
        }

        return $this;
    }
}

src/Form/StaffType.php
<?php

namespace App\Form;

use App\Entity\Staff;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class StaffType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('staff_id', NumberType::class)
            ->add('email', EmailType::class)
            ->add('address', TextType::class)
            ->add('phone',NumberType::class)
            ->add('citizenship',FileType::class,[
                'label'=> 'Citizenship (PDF file)',

                //This means that field is not associated with an entity property
                'mapped'=> false,
                //make required false so that you don't have to reupload file each time you edit
                'required'=>false,
                'constraints' => [
                    new File([
                        'maxSize'=>'1024k',
                        'mimeTypes'=>[
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid pdf document',

                    ])
                ],

            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Confirm Password']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Staff::class,
        ]);
    }
}

src/Controller/StaffController.php
<?php

namespace App\Controller;
use App\Service\FileUploader;
use App\Entity\Staff;
use App\Entity\User;
use App\Form\StaffType;
use App\Form\StaffEditType;
use App\Form\StaffSearchingType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\createNotFoundException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;



class StaffController extends AbstractController
{

	private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }
    /**
     * @Route("/staff", name="staff")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {  $staff = new Staff();
        $form = $this->createForm(StaffSearchingType::class,$staff);
        $form->handleRequest($request);
         if($form->isSubmitted() && $form->isValid()){
            
            $repository = $this->getDoctrine() -> getRepository(Staff::class);
        try{
            $query = $repository->createQueryBuilder('p')
            ->where('p.name LIKE :myname')
            ->orWhere('p.address LIKE :myname')
            ->orWhere('p.phone LIKE :myname')
             ->setParameter('myname', '%'.$staff->getName().'%')
            ->orderBy('p.phone', 'ASC')
            ->getQuery();
            $pagination = $paginator->paginate(
            $staff = $query->getResult(),$request->query->getInt('page', 1), 5
            );
        

         return $this->render('staff/index.html.twig',[
            
            'form' => $form->createView(),
            'pagination' => $pagination,
        ]);
     }
        catch(\Exception $e){
           error_log($e->getMessage());

        }
        }

     $pagination = $paginator->paginate(
    	$staff = $this->getDoctrine()
                    ->getRepository(Staff::class)
                    ->findAll(),$request->query->getInt('page', 1),5);
        if(!$staff){
            throw $this->createNotFoundException(
                "No Staff found "
            );
        }

        return $this->render('staff/index.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView(),
        ]);
    }

        /**
     * @Route("/newstaff", name="newstaff")
     */
    public function registerNew(Request $request, FileUploader $fileUploader)
    {
    	$staff = new Staff();
    	$user = new User();
    	$form = $this->createForm(StaffType::class,$staff);
    	$form->handleRequest($request);
    	if($form->isSubmitted() && $form->isValid()){


            //This is the code to handle files uploaded by the user 
            $citizenshipFile= $form->get('citizenship')->getData();
            if($citizenshipFile){
                $citizenshipFileName = $fileUploader->upload($citizenshipFile);
                $staff->setBrochureFilename($citizenshipFileName);

            }

            try{
    		// Encode the new users password
               $user->setPassword($this->passwordEncoder->encodePassword($user, $staff->getPassword()));
               $user->setEmail($staff->getEmail());
               $user->setName($staff->getName());
                // Set their role
                $user->setRoles(['ROLE_ADMIN']);
            }
            catch(\Exception $e){
                echo $e->getMessage();
            }

    		$em = $this->getDoctrine()->getManager();
    		$em->persist($staff);
    		$em->flush();
    		 $um = $this->getDoctrine()->getManager();
    		 $um->persist($user);
    		 $um->flush();
    		return $this->redirectToRoute('staff');
       	}

       	return $this->render('staff/register.html.twig',[
       		'form' => $form->createView(),
       	]);
    }

     /**
    * @Route("/delstaff/{id}",name="delstaff")
    */
    public function deleteStaff(int $id, LoggerInterface $logger): Response
    {
        $em = $this->getDoctrine()->getManager();
        $staff = $em ->getRepository(Staff::class)->find($id);
        if(!$staff){
            $logger->error("Cannot find the staff with id ");
            throw $this->createNotFoundException(
                "No staff found for id ".$id
            );
        }

        $user = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findOneBy(array('email'=>$staff->getEmail()));  

        if(!$user){
            $logger->error("Cannot find the user with id ");
            throw $this->createNotFoundException(
                "No user found for id ".$id
            );
        }
    try{
        $em -> remove($staff);
        $em ->remove($user);
        $em ->flush();
     }
    catch(\Exception $e)
    {
        $logger->error($e->getMessage());
    }
    return $this->redirectToRoute('staff');
    }

     /**
    * @Route("/editstaff/{id}",name="editstaff")
    */
    public function editStaff(int $id,request $request,FileUploader $fileUploader): Response
    {
        $em = $this->getDoctrine()->getManager();
        $um = $this->getDoctrine()->getManager();
        try{
            $staff = $em ->getRepository(Staff::class)->find($id);
            $user = $um->getRepository(User::class)->findOneBy(array('email'=>$staff->getEmail()));
        // StaffEditType::class is used to get Fully Qualified Class Name App\Form\StaffEditType
            $form = $this->createForm(StaffEditType::class,$staff,[
                'label'=>$staff->getBrochureFilename(),
            ]);
        }
        catch(exception $e){
            print_r($e);
        }
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){


         // Encode the new users password
           $user->setPassword($this->passwordEncoder->encodePassword($user, $staff->getPassword()));
           $user->setEmail($staff->getEmail());
           $user->setName($staff->getName());

           $citizenshipFile=$form->get('citizenship')->getData();
           if($citizenshipFile){
            //if the new citizenship is uploaded then use this condition
                 $citizenshipFileName = $fileUploader->upload($citizenshipFile);
                 $staff->setBrochureFilename($citizenshipFileName);
            }

            // Set their role
            $user->setRoles(['ROLE_ADMIN']);

            $em = $this->getDoctrine()->getManager();
            $em->persist($staff);
            $em->flush();
             $um = $this->getDoctrine()->getManager();
             $um->persist($user);
             $um->flush();
            return $this->redirectToRoute('staff');
        }
        return $this->render('staff/edit.html.twig',[
            'form' => $form->createView(),

        ]);

    }

        /**
    * @Route("/getstaff/{id}",name="getstaff")
    */
    public function getStaff(int $id): Response
    {
        //method to get a single student using an id.

        $staff = $this->getDoctrine()
                    ->getRepository(Staff::class)
                    ->find($id);

        if(!$staff){
            throw $this->createNotFoundException(
                "No product found for id ".$id
            );
        }

        return $this->render('staff/show.html.twig',[
            'staff' =>$staff
        ]);
    }

    /**
    * @Route("/teststaff/{id}", name="teststaff")
    * @Entity("Staff", expr="repository.find(id)")
    */
    public function myStaff(Staff $teststaff)
    // this function uses annotation and getParam / Entity to get the entity row 
    //
    {
        return $this->render('staff/test.html.twig',[
            'staff' => $teststaff
        ]);

    }

}

templates/staff/edit.html.twig
{# templates/registration/index.html.twig #} {% extends 'base.html.twig' %} {%
block body %}
<div class="container content">
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-light mb-3 mt-3">
        <div class="card-body">
          <div class="card-header mb-3">Edit Staff</div>
          {% if is_granted('IS_AUTHENTICATED_FULLY') %}
          {{ form_start(form) }}
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.staff_id, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
           <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.email, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
           <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.citizenship, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.phone, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.address, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-user"></i> Edit
              </button>
              <a href="/dashboard" class="btn btn-danger">
                <i class="fa fa-btn fa-user"></i> Cancel
              </a>

            </div>
          </div>
          {{ form_end(form) }}
          <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
            </div>
        </div>
        {% else %}


      </div>

    </div>
      
      <div>
      <span>You need to be logged in for this content</span>
      </div>
      <a href="{{ path('app_login') }}" class="btn btn-primary">
         Sign Up >></a
      >
       {% endif %}

  </div>

  </div>

</div>

{% endblock %}

templates/staff/index.html.twig
{% extends 'base.html.twig' %} 
{% block body %}
<div class="container content">
  <div class="row scroller ">
  {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <div class="col-md-12 searchholder" >
            {{ form_start(form) }}
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
              <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-user"></i> Search 
              </button>
            </div>
   {{ form_end(form) }}
  </div>
{% endif %}
    <div class="col-md-12">
     {% set error='' %}
      <div class="card bg-light mb-3 mt-3 encompass">
        <div class="card-body" style="overflow:auto">
          <div class="card-header ">List of Staff {{ pagination.getTotalItemCount }}</div>
          {% if is_granted('IS_AUTHENTICATED_FULLY') %}
          <table class="table">
            <tr>
              <th>id</th>
              <th>name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Delete</th>
              <th>Edit</th>
            </tr>
            {% for key, item in pagination %}
            <tr>
              <td>{{ item.staffId }}</td>
              <td><a class="nav-link" href="{{path('getstaff',{id:item.id}) }}">{{ item.name }}</td>
              <td>{{ item.email }}</td>
              <td>{{ item.phone }}</td>
              <td><a class="nav-link" href="{% if  is_granted('ROLE_ADMIN') %} {{path('delstaff',{id:item.id}) }} {% else %} {% set error = 'need to login as admin for delete and edit ' %}  {% endif %} ">Delete</a></td>
              <td><a class="nav-link" href="{% if  is_granted('ROLE_ADMIN') %} {{path('editstaff',{id:item.id}) }} {% else %} {% set error = 'need to login as admin for delete and edit ' %}  {% endif %} ">Edit</a></td> 
            </tr>
            {% endfor %}
          </table>
          {{ knp_pagination_render(pagination) }}
          {{ error }}
          {% else %}
        </div>
      </div>
      <div>
      <span>You need to be logged in for this content</span>
      </div>
      <a href="{{ path('app_login') }}" class="btn btn-primary">
         Sign In</a
      >
       {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/staff/register.html.twig
{# templates/registration/index.html.twig #} {% extends 'base.html.twig' %} {%
block body %}
<div class="container content">
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-light mb-3 mt-3">
        <div class="card-body">
          <div class="card-header mb-3">Add New Staff</div>
          {% if is_granted('ROLE_ADMIN') %}
          {{ form_start(form) }}
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.staff_id, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
           <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.email, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
           <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.citizenship, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.phone, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
            <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.address, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.password.first, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form_group">
            <div class="col-md-12 mb-3">
              {{ form_row(form.password.second, {'attr': {'class':
              'form-control'}}) }}
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">
              <button type="submit" class="btn btn-primary">
                <i class="fa fa-btn fa-user"></i> Register
              </button>
            </div>
          </div>
          {{ form_end(form) }}
        </div>
        {% else %}


      </div>

    </div>
      
      <div>
      <span>You need to be logged as Admin for this content</span>
      </div>
      <a href="{{ path('app_login') }}" class="btn btn-primary">
         Sign In</a
      >
       {% endif %}

  </div>

  </div>

</div>

{% endblock %}

templates/staff/show.html.twig
{% extends 'base.html.twig' %} 
{% block body %}
<div class="container content">
  <div class="row">
    <div class="col-md-12">
      <div class="card bg-gradient-info bg-info text-white mb-3 mt-3">
        <div class="card-body ">
          <div class="card-header h3 ">{{staff.name}}</div>
          {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <ul class="profile left">
            <li> Address : {{ staff.Address }}</li>
            <li> Staff Id : {{ staff.staffId }}</li>
            <li class ="bold"> Email: {{ staff.email }}</li>
            <li> Phone: {{ staff.phone }}</li>
            {% if staff.brochureFilename %}
            <li><a href="{{ asset('uploads/citizenships/' ~ staff.brochureFilename) }}" style="color:red">View Citizenship (PDF)</a></li>
            {% else %}
              <li>No Citizenship Uploaded</li>
            {% endif %}
            </ul>
          {% else %}
        </div>

      </div>
    
      <a href="{{ path('app_login') }}" class="btn btn-info">
        You need to login to see the list 😜😜 >></a
      >
       {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/staff/test.html.twig
Hello from staff {{ staff.name }} with email {{ staff.password }}